#ifndef Game_PKM_Tags_h__
#define Game_PKM_Tags_h__

NS_BEGIN(Game_PKM)

// Texture
WNAME_TAG(PROTO_COM_TEX_DUMMY_BLACK, L"Prototype_Component_Texture_Dummy_Black");
WNAME_TAG(PROTO_COM_TEX_DUMMY_MAGENTA, L"Prototype_Component_Texture_Dummy_Magenta");
WNAME_TAG(PROTO_COM_TEX_DUMMY_WHITE, L"Prototype_Component_Texture_Dummy_White");

WNAME_TAG(PROTO_COM_TEX_BACKGROUND, L"Prototype_Component_Texture_BackGround");
WNAME_TAG(PROTO_COM_TEX_TERRAIN_DIFF, L"Prototype_Component_Texture_Terrain_Diffuse");
WNAME_TAG(PROTO_COM_TEX_TERRAIN_MASK, L"Prototype_Component_Texture_Terrain_Mask");
WNAME_TAG(PROTO_COM_TEX_TERRAIN_BRUSH, L"Prototype_Component_Texture_Terrain_Brush");
WNAME_TAG(PROTO_COM_TEX_SKY, L"Prototype_Component_Texture_Sky");
WNAME_TAG(PROTO_COM_TEX_SNOW, L"Prototype_Component_Texture_Snow");

WNAME_TAG(PROTO_COM_TEX_WATER, L"Prototype_Component_Texture_Water");
WNAME_TAG(PROTO_COM_TEX_CLOUD, L"Prototype_Component_Texture_Cloud");
WNAME_TAG(PROTO_COM_TEX_FIELD_GRASS, L"Prototype_Component_Texture_FieldGrass");

WNAME_TAG(PROTO_COM_TEX_TITLE_PBGF_DIFF, L"Prototype_Component_Texture_Title_pbgf_Diff");
WNAME_TAG(PROTO_COM_TEX_TITLE_LOGO_DIFF, L"Prototype_Component_Texture_Title_Logo_Diff");
WNAME_TAG(PROTO_COM_TEX_TITLE_PBTN_DIFF, L"Prototype_Component_Texture_Title_pbtn_Diff");
WNAME_TAG(PROTO_COM_TEX_TITLE_PIKA, L"Prototype_Component_Texture_Title_Pika");
WNAME_TAG(PROTO_COM_TEX_STAR, L"Prototype_Component_Texture_Star");
WNAME_TAG(PROTO_COM_TEX_TITLE_BG, L"Prototype_Component_Texture_Title_BackGround");

WNAME_TAG(PROTO_COM_TEX_CURSOR, L"Prototype_Component_Texture_Cursor");

WNAME_TAG(PROTO_COM_TEX_MENU_BALL, L"Prototype_Component_Texture_Menu_Ball");
WNAME_TAG(PROTO_COM_TEX_MENU_PARTNER, L"Prototype_Component_Texture_Menu_Partner");
WNAME_TAG(PROTO_COM_TEX_MENU_DEX, L"Prototype_Component_Texture_Menu_Dex");
WNAME_TAG(PROTO_COM_TEX_MENU_BAG, L"Prototype_Component_Texture_Menu_Bag");
WNAME_TAG(PROTO_COM_TEX_MENU_ENTRY, L"Prototype_Component_Texture_Menu_Entry");
WNAME_TAG(PROTO_COM_TEX_MENU_LINK, L"Prototype_Component_Texture_Menu_Link");
WNAME_TAG(PROTO_COM_TEX_MENU_REPORT, L"Prototype_Component_Texture_Menu_Report");

WNAME_TAG(PROTO_COM_TEX_GET_BUTTON, L"Prototype_Component_Texture_Get_Button");
WNAME_TAG(PROTO_COM_TEX_GET_ICON, L"Prototype_Component_Texture_Get_Icon");
WNAME_TAG(PROTO_COM_TEX_GET_INFO, L"Prototype_Component_Texture_Get_Info");
WNAME_TAG(PROTO_COM_TEX_GET_INFO2, L"Prototype_Component_Texture_Get_Info2");
WNAME_TAG(PROTO_COM_TEX_GET_LINE_FILL, L"Prototype_Component_Texture_Get_Line_Fill");
WNAME_TAG(PROTO_COM_TEX_GET_LINE_BACK, L"Prototype_Component_Texture_Get_Line_Back");
WNAME_TAG(PROTO_COM_TEX_GET_LINE2_FILL, L"Prototype_Component_Texture_Get_Line2_Fill");
WNAME_TAG(PROTO_COM_TEX_GET_LINE2_BACK, L"Prototype_Component_Texture_Get_Line2_Back");
WNAME_TAG(PROTO_COM_TEX_GET_TEXT_LV, L"Prototype_Component_Texture_Get_Text_LV");
WNAME_TAG(PROTO_COM_TEX_GET_TEXT_NUM, L"Prototype_Component_Texture_Get_Text_Number");

WNAME_TAG(PROTO_COM_TEX_BTL_FADE_COL, L"Prototype_Component_Texture_Battle_Fade_Color");
WNAME_TAG(PROTO_COM_TEX_BTL_FADE_NOISE, L"Prototype_Component_Texture_Battle_Fade_Noise");
WNAME_TAG(PROTO_COM_TEX_BTL_FADE_OUT, L"Prototype_Component_Texture_Battle_Fade_Out");
WNAME_TAG(PROTO_COM_TEX_BTL_FADE_LINE, L"Prototype_Component_Texture_Battle_Fade_Line");
WNAME_TAG(PROTO_COM_TEX_BTL_FADE_MASK, L"Prototype_Component_Texture_Battle_Fade_Mask");

WNAME_TAG(PROTO_COM_TEX_BTL_BTN_FIGHT, L"Prototype_Component_Texture_Battle_Button_Fight");
WNAME_TAG(PROTO_COM_TEX_BTL_BTN_POKE, L"Prototype_Component_Texture_Battle_Button_Poke");
WNAME_TAG(PROTO_COM_TEX_BTL_BTN_BAG, L"Prototype_Component_Texture_Battle_Button_Bag");
WNAME_TAG(PROTO_COM_TEX_BTL_PLAYERPLATE, L"Prototype_Component_Texture_Battle_PlayerPlate");
WNAME_TAG(PROTO_COM_TEX_BTL_ENEMYPLATE, L"Prototype_Component_Texture_Battle_EnemyPlate");
WNAME_TAG(PROTO_COM_TEX_BTL_BALLPLATE, L"Prototype_Component_Texture_Battle_BallPlate");
WNAME_TAG(PROTO_COM_TEX_BTL_BALLICON, L"Prototype_Component_Texture_Battle_BallIcon");
WNAME_TAG(PROTO_COM_TEX_BTL_NUM, L"Prototype_Component_Texture_Battle_Number");
WNAME_TAG(PROTO_COM_TEX_BTL_NUM_SLASH, L"Prototype_Component_Texture_Battle_Number_Slash");
WNAME_TAG(PROTO_COM_TEX_STATUS_GENDER, L"Prototype_Component_Texture_Status_Gender");

WNAME_TAG(PROTO_COM_TEX_BTL_MSGBOX, L"Prototype_Component_Texture_Battle_MsgBox");
WNAME_TAG(PROTO_COM_TEX_BTL_MSGICON, L"Prototype_Component_Texture_Battle_MsgIcon");

WNAME_TAG(PROTO_COM_TEX_BTL_MOVE, L"Prototype_Component_Texture_Battle_Move");
WNAME_TAG(PROTO_COM_TEX_BTL_MOVEICON, L"Prototype_Component_Texture_Battle_MoveIcon");
WNAME_TAG(PROTO_COM_TEX_BTL_MOVESHADOW, L"Prototype_Component_Texture_Battle_MoveShadow");

WNAME_TAG(PROTO_COM_TEX_ENTRY_BG_PLATE, L"Prototype_Component_Texture_Entry_BG_Plate");
WNAME_TAG(PROTO_COM_TEX_ENTRY_ICON, L"Prototype_Component_Texture_Entry_Icon");
WNAME_TAG(PROTO_COM_TEX_ENTRY_PLATE, L"Prototype_Component_Texture_Entry_Plate");

WNAME_TAG(PROTO_COM_TEX_POKEMON_ICON, L"Prototype_Component_Texture_Pokemon_Icon");
WNAME_TAG(PROTO_COM_TEX_LOADING_MARK, L"Prototype_Component_Texture_Loading_Mark");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_BG_00, L"Prototype_Component_Texture_Loading_Setting_BG_00");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_BG_01, L"Prototype_Component_Texture_Loading_Setting_BG_01");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_GEAR_00, L"Prototype_Component_Texture_Loading_Setting_Gear_00");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_GEAR_01, L"Prototype_Component_Texture_Loading_Setting_Gear_01");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_GEAR_02, L"Prototype_Component_Texture_Loading_Setting_Gear_02");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_GEAR_03, L"Prototype_Component_Texture_Loading_Setting_Gear_03");
WNAME_TAG(PROTO_COM_TEX_LOADING_SETTING_GEAR_04, L"Prototype_Component_Texture_Loading_Setting_Gear_04");

WNAME_TAG(PROTO_COM_TEX_PLACE_NAME, L"Prototype_Component_Texture_Place_Name");

WNAME_TAG(PROTO_COM_TEX_MSGBOX_BG, L"Prototype_Component_Texture_MsgBox_BG");
WNAME_TAG(PROTO_COM_TEX_MSGBOX_ICON, L"Prototype_Component_Texture_MsgBox_Icon");

WNAME_TAG(PROTO_COM_TEX_STATUS_GAUGE_BACK, L"Prototype_Component_Texture_Status_Gauge_Back");
WNAME_TAG(PROTO_COM_TEX_STATUS_GAUGE_FRAME, L"Prototype_Component_Texture_Status_Gauge_Frame");
WNAME_TAG(PROTO_COM_TEX_STATUS_GAUGE_OUTLINE, L"Prototype_Component_Texture_Status_Gauge_Outline");

WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_0_LINE702_SML_O, L"Prototype_Component_Texture_Effect_Ball_Absorb_0_Line702_Sml_O");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_0_MASK702_O, L"Prototype_Component_Texture_Effect_Ball_Absorb_0_Mask702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_1_CIRCLE004_SML_M, L"Prototype_Component_Texture_Effect_Ball_Absorb_1_Circle004_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_1_CIRCLE005_SML_M, L"Prototype_Component_Texture_Effect_Ball_Absorb_1_Circle005_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_2_FIRE003_M, L"Prototype_Component_Texture_Effect_Ball_Absorb_2_Fire003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_2_HIT011_M, L"Prototype_Component_Texture_Effect_Ball_Absorb_2_Hit011_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_ABSORB_3_FLOW701_O, L"Prototype_Component_Texture_Effect_Ball_Absorb_3_Flow701_O");

WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_0_MASK702_O, L"Prototype_Component_Texture_Effect_Ball_Hit_0_Mask702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_0_SMOKE002_M, L"Prototype_Component_Texture_Effect_Ball_Hit_0_Smoke002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_0_SMOKE005_M, L"Prototype_Component_Texture_Effect_Ball_Hit_0_Smoke005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_0_SMOKE203_A, L"Prototype_Component_Texture_Effect_Ball_Hit_0_Smoke203_A");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_0_SMOKE702_O, L"Prototype_Component_Texture_Effect_Ball_Hit_0_Smoke702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_1_CIRCLE003_SML_M, L"Prototype_Component_Texture_Effect_Ball_Hit_1_Circle003_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BALL_HIT_1_FLASH001_SML_M, L"Prototype_Component_Texture_Effect_Ball_Hit_1_Flash001_Sml_M");

WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_0_BLUR003_SML_M, L"Prototype_Component_Texture_Effect_Capture_Failed_0_Blur003_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_0_LINE701_O, L"Prototype_Component_Texture_Effect_Capture_Failed_0_Line701_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_0_MASK702_O, L"Prototype_Component_Texture_Effect_Capture_Failed_0_Mask702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_0_SMOKE702_O, L"Prototype_Component_Texture_Effect_Capture_Failed_0_Smoke702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_1_CIRCLE004_SML_M, L"Prototype_Component_Texture_Effect_Capture_Failed_1_Circle004_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_1_CIRCLE005_SML_M, L"Prototype_Component_Texture_Effect_Capture_Failed_1_Circle005_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_2_DUST701_O, L"Prototype_Component_Texture_Effect_Capture_Failed_2_Dust701_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_2_HIT011_M, L"Prototype_Component_Texture_Effect_Capture_Failed_2_Hit011_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_2_SMOKE703_O, L"Prototype_Component_Texture_Effect_Capture_Failed_2_Smoke703_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_FAILED_2_WATER009_M, L"Prototype_Component_Texture_Effect_Capture_Failed_2_Water009_M");

WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_0_LINE702_O, L"Prototype_Component_Texture_Effect_Capture_Hit_0_Line702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_0_MASK702_O, L"Prototype_Component_Texture_Effect_Capture_Hit_0_Mask702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_0_MASK703_O, L"Prototype_Component_Texture_Effect_Capture_Hit_0_Mask703_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_0_SMOKE702_O, L"Prototype_Component_Texture_Effect_Capture_Hit_0_Smoke702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_1_CIRCLE005_M, L"Prototype_Component_Texture_Effect_Capture_Hit_1_Circle005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_1_FLASH001_SML_M, L"Prototype_Component_Texture_Effect_Capture_Hit_1_Flash001_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_2_DUST701_O, L"Prototype_Component_Texture_Effect_Capture_Hit_2_Dust701_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_2_SMOKE001_M, L"Prototype_Component_Texture_Effect_Capture_Hit_2_Smoke001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_2_TRANSFORM001_M, L"Prototype_Component_Texture_Effect_Capture_Hit_2_Transform001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_HIT_3_CLOUD001_M, L"Prototype_Component_Texture_Effect_Capture_Hit_3_Cloud001_M");

WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_SUCCESS_0_LINE701_O, L"Prototype_Component_Texture_Effect_Capture_Success_0_Line701_O");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_SUCCESS_0_MASK003_M, L"Prototype_Component_Texture_Effect_Capture_Success_0_Mask003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_SUCCESS_0_MA_STAR001_SML_M, L"Prototype_Component_Texture_Effect_Capture_Success_0_Ma_Star001_Sml_M");
WNAME_TAG(PROTO_COM_TEX_EFT_CAPTURE_SUCCESS_1_CIRCLE001_SML_M, L"Prototype_Component_Texture_Effect_Capture_Success_1_Circle001_Sml_M");

WNAME_TAG(PROTO_COM_TEX_EFT_HIT_0_LINE701_O, L"Prototype_Component_Texture_Effect_Hit_0_Line701_O");
WNAME_TAG(PROTO_COM_TEX_EFT_HIT_0_RING001_M, L"Prototype_Component_Texture_Effect_Hit_0_Ring001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_HIT_1_CIRCLE002_M, L"Prototype_Component_Texture_Effect_Hit_1_Circle002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_HIT_1_CIRCLE004_M, L"Prototype_Component_Texture_Effect_Hit_1_Circle004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_HIT_2_HIT014_M, L"Prototype_Component_Texture_Effect_Hit_2_Hit014_M");
WNAME_TAG(PROTO_COM_TEX_EFT_HIT_2_WIND001_M, L"Prototype_Component_Texture_Effect_Hit_2_Wind001_M");

WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_HIT009_M, L"Prototype_Component_Texture_Effect_Thunder_2_Hit009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_HIT014_M, L"Prototype_Component_Texture_Effect_Thunder_2_Hit014_M");
WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_THUNDER009_M, L"Prototype_Component_Texture_Effect_Thunder_2_Thunder009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_THUNDER010_M, L"Prototype_Component_Texture_Effect_Thunder_2_Thunder010_M");
WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_THUNDER702_O, L"Prototype_Component_Texture_Effect_Thunder_2_Thunder702_O");
WNAME_TAG(PROTO_COM_TEX_EFT_THUNDER_2_THUNDER703_O, L"Prototype_Component_Texture_Effect_Thunder_2_Thunder703_O");

WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_0_BUBBLE201_A, L"Prototype_Component_Texture_Effect_Bubble_0_Bubble201_A");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_0_SMOKE002_M, L"Prototype_Component_Texture_Effect_Bubble_0_Smoke002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_0_SMOKE202_A, L"Prototype_Component_Texture_Effect_Bubble_0_Smoke202_A");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_1_CIRCLE001_M, L"Prototype_Component_Texture_Effect_Bubble_1_Circle001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_BUBBLE003_M, L"Prototype_Component_Texture_Effect_Bubble_2_Bubble003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_BUBBLE004_M, L"Prototype_Component_Texture_Effect_Bubble_2_Bubble004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_BUBBLE009_M, L"Prototype_Component_Texture_Effect_Bubble_2_Bubble009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_HIT015_M, L"Prototype_Component_Texture_Effect_Bubble_2_Hit015_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_LINE002_M, L"Prototype_Component_Texture_Effect_Bubble_2_Line002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_SMOKE001_M, L"Prototype_Component_Texture_Effect_Bubble_2_Smoke001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_WATER004_M, L"Prototype_Component_Texture_Effect_Bubble_2_Water004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_WATER006_M, L"Prototype_Component_Texture_Effect_Bubble_2_Water006_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_WATER011_M, L"Prototype_Component_Texture_Effect_Bubble_2_Water011_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_WATER012_M, L"Prototype_Component_Texture_Effect_Bubble_2_Water012_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BUBBLE_2_WATER013_M, L"Prototype_Component_Texture_Effect_Bubble_2_Water013_M");

WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_1_CIRCLE004_M, L"Prototype_Component_Texture_Effect_Fire_1_Circle004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_2_FIRE003_M, L"Prototype_Component_Texture_Effect_Fire_2_Fire003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_2_FIRE005_M, L"Prototype_Component_Texture_Effect_Fire_2_Fire005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_2_FIRE008_M, L"Prototype_Component_Texture_Effect_Fire_2_Fire008_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_2_FIRE009_M, L"Prototype_Component_Texture_Effect_Fire_2_Fire009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_2_RING004_M, L"Prototype_Component_Texture_Effect_Fire_2_Ring004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FIRE_3_FLOW005_A, L"Prototype_Component_Texture_Effect_Fire_3_Flow005_A");

WNAME_TAG(PROTO_COM_TEX_EFT_BEAM_3_FLOW006_M, L"Prototype_Component_Texture_Effect_Beam_3_Flow006_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BEAM_3_ICE001_M, L"Prototype_Component_Texture_Effect_Beam_3_Ice001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BEAM_3_LASER001_M, L"Prototype_Component_Texture_Effect_Beam_3_Laser001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BEAM_3_LASER002_M, L"Prototype_Component_Texture_Effect_Beam_3_Laser002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_BEAM_3_SHOCK001_M, L"Prototype_Component_Texture_Effect_Beam_3_Shock001_M");

WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_0_MASK003_M, L"Prototype_Component_Texture_Effect_Floor_0_Mask003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_BLUR001_M, L"Prototype_Component_Texture_Effect_Floor_3_Blur001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_CLOUD007_M, L"Prototype_Component_Texture_Effect_Floor_3_Cloud007_M");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_CLOUD201_A, L"Prototype_Component_Texture_Effect_Floor_3_Cloud201_A");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_FLOOR204_BIG_A, L"Prototype_Component_Texture_Effect_Floor_3_Floor204_Big_A");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_FLOOR206_A, L"Prototype_Component_Texture_Effect_Floor_3_Floor206_A");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_ROCK203_A, L"Prototype_Component_Texture_Effect_Floor_3_Rock203_A");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_3_WHITE202_A, L"Prototype_Component_Texture_Effect_Floor_3_White202_A");
WNAME_TAG(PROTO_COM_TEX_EFT_FLOOR_CMN_HT003_M_LTA, L"Prototype_Component_Texture_Effect_Floor_Cmn_Ht003_M_Lta");

WNAME_TAG(PROTO_COM_TEX_EFT_PUNCH_1_CIRCLE001_M, L"Prototype_Component_Texture_Effect_Punch_1_Circle001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_PUNCH_1_CIRCLE005_M, L"Prototype_Component_Texture_Effect_Punch_1_Circle005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_PUNCH_1_RING009_M, L"Prototype_Component_Texture_Effect_Punch_1_Ring009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_PUNCH_2_HIT008_M, L"Prototype_Component_Texture_Effect_Punch_2_Hit008_M");
WNAME_TAG(PROTO_COM_TEX_EFT_PUNCH_2_MARK701_O, L"Prototype_Component_Texture_Effect_Punch_2_Mark701_O");

WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_0_RING001_M, L"Prototype_Component_Texture_Effect_Rainbow_0_Ring001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_0_RING004_M, L"Prototype_Component_Texture_Effect_Rainbow_0_Ring004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_1_CIRCLE001_M, L"Prototype_Component_Texture_Effect_Rainbow_1_Circle001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_1_CIRCLE004_M, L"Prototype_Component_Texture_Effect_Rainbow_1_Circle004_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_1_CIRCLE005_M, L"Prototype_Component_Texture_Effect_Rainbow_1_Circle005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_1_RING012_M, L"Prototype_Component_Texture_Effect_Rainbow_1_Ring012_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_2_BOM002_M, L"Prototype_Component_Texture_Effect_Rainbow_2_Bom002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_2_HIT010_M, L"Prototype_Component_Texture_Effect_Rainbow_2_Hit010_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_2_WATER006_M, L"Prototype_Component_Texture_Effect_Rainbow_2_Water006_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_2_WIND001_M, L"Prototype_Component_Texture_Effect_Rainbow_2_Wind001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_RAINBOW_3_COLOR001_M, L"Prototype_Component_Texture_Effect_Rainbow_3_Color001_M");

WNAME_TAG(PROTO_COM_TEX_EFT_SONIC_0_MASK003_M, L"Prototype_Component_Texture_Effect_Sonic_0_Mask003_M");
WNAME_TAG(PROTO_COM_TEX_EFT_SONIC_0_RING006_M, L"Prototype_Component_Texture_Effect_Sonic_0_Ring006_M");

WNAME_TAG(PROTO_COM_TEX_EFT_SURFBOARD_EW730_SURFBOARD_U, L"Prototype_Component_Texture_Effect_Surfboard_Ew730_Surfboard_U");

WNAME_TAG(PROTO_COM_TEX_EFT_ZIPPY_ZAP_0_MASK005_M, L"Prototype_Component_Texture_Effect_Zippy_Zap_0_Mask005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_ZIPPY_ZAP_1_CIRCLE005_M, L"Prototype_Component_Texture_Effect_Zippy_Zap_1_Circle005_M");
WNAME_TAG(PROTO_COM_TEX_EFT_ZIPPY_ZAP_2_HIT014_M, L"Prototype_Component_Texture_Effect_Zippy_Zap_2_Hit014_M");
WNAME_TAG(PROTO_COM_TEX_EFT_ZIPPY_ZAP_2_THUNDER011_M, L"Prototype_Component_Texture_Effect_Zippy_Zap_2_Thunder011_M");
WNAME_TAG(PROTO_COM_TEX_EFT_ZIPPY_ZAP_2_THUNDER201_A, L"Prototype_Component_Texture_Effect_Zippy_Zap_2_Thunder201_A");

WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_0_WATER002_M,	L"Prototype_Component_Texture_Effect_Wave_0_Water002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_0_DAST001_M,	L"Prototype_Component_Texture_Effect_Wave_0_Dast001_M");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_1_CIRCLE002_M,	L"Prototype_Component_Texture_Effect_Wave_1_Circle002_M");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_2_WATER009_M,	L"Prototype_Component_Texture_Effect_Wave_2_Water009_M");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_3_BLUR202_A,	L"Prototype_Component_Texture_Effect_Wave_3_Blur202_A");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_3_CLOUD204_A,	L"Prototype_Component_Texture_Effect_Wave_3_Cloud204_A");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_3_FLOW011_M,	L"Prototype_Component_Texture_Effect_Wave_3_Flow011_M");
WNAME_TAG(PROTO_COM_TEX_EFT_WAVE_3_FLOW013_M,	L"Prototype_Component_Texture_Effect_Wave_3_Flow013_M");



// Shader
WNAME_TAG(PROTO_COM_SHADER_VTXTEX, L"Prototype_Component_Shader_VtxTex");
WNAME_TAG(PROTO_COM_SHADER_VTXNORTEX, L"Prototype_Component_Shader_VtxNorTex");
WNAME_TAG(PROTO_COM_SHADER_VTXMESH, L"Prototype_Component_Shader_VtxMesh");
WNAME_TAG(PROTO_COM_SHADER_VTXANIMMESH, L"Prototype_Component_Shader_VtxAnimMesh");
WNAME_TAG(PROTO_COM_SHADER_VTXCUBE, L"Prototype_Component_Shader_VtxCube");
WNAME_TAG(PROTO_COM_SHADER_VTXRECTINST, L"Prototype_Component_Shader_VtxRectInstance");
WNAME_TAG(PROTO_COM_SHADER_VTXPOINTINST, L"Prototype_Component_Shader_VtxPointInstance");
WNAME_TAG(PROTO_COM_SHADER_EFFECT_M1, L"Prototype_Component_Shader_Effect_M1");

WNAME_TAG(PROTO_COM_SHADER_PLAYER_LGPE, L"Prototype_Component_Shader_Player_LGPE");
WNAME_TAG(PROTO_COM_SHADER_POKEMON, L"Prototype_Component_Shader_Pokemon");
WNAME_TAG(PROTO_COM_SHADER_HUMAN, L"Prototype_Component_Shader_Human");
WNAME_TAG(PROTO_COM_SHADER_MAP, L"Prototype_Component_Shader_Map");
WNAME_TAG(PROTO_COM_SHADER_UI, L"Prototype_Component_Shader_UI");
WNAME_TAG(PROTO_COM_SHADER_VTXUIINST, L"Prototype_Component_Shader_VtxUIInstance");
WNAME_TAG(PROTO_COM_SHADER_UIIMAGE, L"Prototype_Component_Shader_UIImage");
WNAME_TAG(PROTO_COM_SHADER_UIBUTTON_GLOW, L"Prototype_Component_Shader_UI_Button_Glow");
WNAME_TAG(PROTO_COM_SHADER_UIBUTTON_LAYERED, L"Prototype_Component_Shader_UI_Button_Layered");
WNAME_TAG(PROTO_COM_SHADER_UIBUTTON_ENTRY, L"Prototype_Component_Shader_UI_Button_Entry");
WNAME_TAG(PROTO_COM_SHADER_PARTICLE3D, L"Prototype_Component_Shader_Particle3D");
WNAME_TAG(PROTO_COM_SHADER_EFFECT_BEAM, L"Prototype_Component_Shader_Effect_Beam");
WNAME_TAG(PROTO_COM_SHADER_TRAIL, L"Prototype_Component_Shader_Trail");
WNAME_TAG(PROTO_COM_SHADER_WATER, L"Prototype_Component_Shader_Water");
WNAME_TAG(PROTO_COM_SHADER_FIELD_GRASS, L"Prototype_Component_Shader_FieldGrass");



// VIBuffer & Model
WNAME_TAG(PROTO_COM_VIBUFFER_RECT, L"Prototype_Component_VIBuffer_Rect");
WNAME_TAG(PROTO_COM_VIBUFFER_TERRAIN, L"Prototype_Component_VIBuffer_Terrain");
WNAME_TAG(PROTO_COM_VIBUFFER_CUBE, L"Prototype_Component_VIBuffer_Cube");
WNAME_TAG(PROTO_COM_VIBUFFER_INST_SNOW, L"Prototype_Component_VIBuffer_Instance_Snow");
WNAME_TAG(PROTO_COM_VIBUFFER_INST_EXPLOSION, L"Prototype_Component_VIBuffer_Instance_Explosion");
WNAME_TAG(PROTO_COM_VIBUFFER_INST_STAR, L"Prototype_Component_VIBuffer_Instance_Star");
WNAME_TAG(PROTO_COM_VIBUFFER_INST_EFFECT, L"Prototype_Component_VIBuffer_Instance_Effect");
WNAME_TAG(PROTO_COM_VIBUFFER_INST_PARTICLE3D, L"Prototype_Component_VIBuffer_Instance_Particle3D");
WNAME_TAG(PROTO_COM_VIBUFFER_TRAIL, L"Prototype_Component_VIBuffer_Trail");
WNAME_TAG(PROTO_COM_VIBUFFER_XZPLANE, L"Prototype_Component_VIBuffer_XZPlane");
WNAME_TAG(PROTO_COM_VIBUFFER_FIELD_GRASS_INST, L"Prototype_Component_VIBuffer_FieldGrass_Instance");
WNAME_TAG(PROTO_COM_MODEL_FIONA, L"Prototype_Component_Model_Fiona");
WNAME_TAG(PROTO_COM_MODEL_FORKLIFT, L"Prototype_Component_Model_ForkLift");

WNAME_TAG(PROTO_COM_MODEL_PM0001_00, L"Prototype_Component_Model_ÀÌ»óÇØ¾¾");
WNAME_TAG(PROTO_COM_MODEL_PM0004_00, L"Prototype_Component_Model_ÆÄÀÌ¸®");
WNAME_TAG(PROTO_COM_MODEL_PM0007_00, L"Prototype_Component_Model_²¿ºÎ±â");
WNAME_TAG(PROTO_COM_MODEL_PM0010_00, L"Prototype_Component_Model_Ä³ÅÍÇÇ");
WNAME_TAG(PROTO_COM_MODEL_PM0025_00, L"Prototype_Component_Model_ÇÇÄ«Ãò");
WNAME_TAG(PROTO_COM_MODEL_PM0041_00, L"Prototype_Component_Model_ÁÖ¹î");
WNAME_TAG(PROTO_COM_MODEL_PM0043_00, L"Prototype_Component_Model_¶Ñ¹÷ÃÝ");
WNAME_TAG(PROTO_COM_MODEL_PM0059_00, L"Prototype_Component_Model_À©µð");
WNAME_TAG(PROTO_COM_MODEL_PM0074_00, L"Prototype_Component_Model_²¿¸¶µ¹");
WNAME_TAG(PROTO_COM_MODEL_PM0095_00, L"Prototype_Component_Model_·Õ½ºÅæ");
WNAME_TAG(PROTO_COM_MODEL_PM0121_00, L"Prototype_Component_Model_¾ÆÄí½ºÅ¸");
WNAME_TAG(PROTO_COM_MODEL_PM0130_00, L"Prototype_Component_Model_°¼¶óµµ½º");

WNAME_TAG(PROTO_COM_MODEL_HERO, L"Prototype_Component_Model_Hero");
WNAME_TAG(PROTO_COM_MODEL_HEROINE, L"Prototype_Component_Model_Heroine");
WNAME_TAG(PROTO_COM_MODEL_DOCTOR, L"Prototype_Component_Model_Doctor");
WNAME_TAG(PROTO_COM_MODEL_PPL_ROCK, L"Prototype_Component_Model_People_Rock");
WNAME_TAG(PROTO_COM_MODEL_PPL_WATER, L"Prototype_Component_Model_People_Water");
WNAME_TAG(PROTO_COM_MODEL_PPL_FAT, L"Prototype_Component_Model_People_Fat");
WNAME_TAG(PROTO_COM_MODEL_PPL_NURSE, L"Prototype_Component_Model_People_Nurse");
WNAME_TAG(PROTO_COM_MODEL_PPL_JUVENILES, L"Prototype_Component_Model_People_Juveniles");
WNAME_TAG(PROTO_COM_MODEL_PPL_SHORTPANTS, L"Prototype_Component_Model_People_Shortpants");

WNAME_TAG(PROTO_COM_MODEL_MAP_TOWN01, L"Prototype_Component_Model_Map_Town01");
WNAME_TAG(PROTO_COM_MODEL_MAP_TOWN02, L"Prototype_Component_Model_Map_Town02");
WNAME_TAG(PROTO_COM_MODEL_MAP_ROAD01, L"Prototype_Component_Model_Map_Road01");

WNAME_TAG(PROTO_COM_MODEL_BMAP_TOWN, L"Prototype_Component_Model_BMap_Town");
WNAME_TAG(PROTO_COM_MODEL_BMAP_GRASS, L"Prototype_Component_Model_BMap_Grass");

WNAME_TAG(PROTO_COM_MODEL_MONSTER_BALL, L"Prototype_Component_Model_Monster_Ball");
WNAME_TAG(PROTO_COM_MODEL_CAPTURE_RING, L"Prototype_Component_Model_Capture_Ring");
WNAME_TAG(PROTO_COM_MODEL_FIELD_GRASS, L"Prototype_Component_Model_FieldGrass");

WNAME_TAG(PROTO_COM_MODEL_STATIC_AT_BEAM, L"Prototype_Component_Model_Static_At_Beam");
WNAME_TAG(PROTO_COM_MODEL_STATIC_BALL, L"Prototype_Component_Model_Static_Ball");
WNAME_TAG(PROTO_COM_MODEL_STATIC_BALLOON, L"Prototype_Component_Model_Static_Balloon");
WNAME_TAG(PROTO_COM_MODEL_STATIC_CONE, L"Prototype_Component_Model_Static_Cone");
WNAME_TAG(PROTO_COM_MODEL_STATIC_CUBE, L"Prototype_Component_Model_Static_Cube");
WNAME_TAG(PROTO_COM_MODEL_STATIC_CYLINDER, L"Prototype_Component_Model_Static_Cylinder");
WNAME_TAG(PROTO_COM_MODEL_STATIC_DF_BEAM, L"Prototype_Component_Model_Static_Df_Beam");
WNAME_TAG(PROTO_COM_MODEL_STATIC_RING, L"Prototype_Component_Model_Static_Ring");
WNAME_TAG(PROTO_COM_MODEL_STATIC_SONIC, L"Prototype_Component_Model_Static_Sonic");
WNAME_TAG(PROTO_COM_MODEL_STATIC_SPHERE, L"Prototype_Component_Model_Static_Sphere");
WNAME_TAG(PROTO_COM_MODEL_STATIC_STONE, L"Prototype_Component_Model_Static_Stone");
WNAME_TAG(PROTO_COM_MODEL_STATIC_SURF, L"Prototype_Component_Model_Static_Surf");

// Navigation & Collider
WNAME_TAG(PROTO_COM_NAVIGATION_TERRAIN, L"Prototype_Component_Navigation_Terrain");
WNAME_TAG(PROTO_COM_NAVIGATION_MAP, L"Prototype_Component_Navigation_Map");
WNAME_TAG(PROTO_COM_COLLIDER_AABB, L"Prototype_Component_Collider_AABB");
WNAME_TAG(PROTO_COM_COLLIDER_OBB, L"Prototype_Component_Collider_OBB");
WNAME_TAG(PROTO_COM_COLLIDER_SPHERE, L"Prototype_Component_Collider_Sphere");



// Interaction
WNAME_TAG(PROTO_COM_INTERACTION_DIALOGUE, L"Prototype_Component_Interaction_Dialogue");
WNAME_TAG(PROTO_COM_INTERACTION_ENCOUNTER, L"Prototype_Component_Interaction_Encounter");
WNAME_TAG(PROTO_COM_INTERACTION_BALLHIT, L"Prototype_Component_Interaction_BallHit");
WNAME_TAG(PROTO_COM_INTERACTION_DIALOGUE_BATTLE, L"Prototype_Component_Interaction_Dialogue_Battle");
WNAME_TAG(PROTO_COM_INTERACTION_EVENT_SEQUENCE, L"Prototype_Component_Interaction_EventSequence");


// Layer
WNAME_TAG(LAYER_PERSISTENT, L"Layer_Persistent");
WNAME_TAG(LAYER_BACKGROUND, L"Layer_BackGround");
WNAME_TAG(LAYER_CAMERA, L"Layer_Camera");
WNAME_TAG(LAYER_PLAYER, L"Layer_Player");
WNAME_TAG(LAYER_MONSTER, L"Layer_Monster");
WNAME_TAG(LAYER_NPC, L"Layer_NPC");
WNAME_TAG(LAYER_INTERACTABLE, L"Layer_Interactable");
WNAME_TAG(LAYER_EFFECT, L"Layer_Effect");
WNAME_TAG(LAYER_UI, L"Layer_UI");



// Object
WNAME_TAG(PROTO_OBJ_BACKGROUND, L"Prototype_GameObject_BackGround");
WNAME_TAG(PROTO_OBJ_TITLE_BG, L"Prototype_GameObject_Title_BG");
WNAME_TAG(PROTO_OBJ_LOGO_MONSTER, L"Prototype_GameObject_Logo_Monster");
WNAME_TAG(PROTO_OBJ_WATERPLANE, L"Prototype_GameObject_WaterPlane");

WNAME_TAG(PROTO_OBJ_TERRAIN, L"Prototype_GameObject_Terrain");
WNAME_TAG(PROTO_OBJ_CAMERA_FREE, L"Prototype_GameObject_Camera_Free");
WNAME_TAG(PROTO_OBJ_MONSTER, L"Prototype_GameObject_Monster");
WNAME_TAG(PROTO_OBJ_FORKLIFT, L"Prototype_GameObject_ForkLift");
WNAME_TAG(PROTO_OBJ_PLAYER, L"Prototype_GameObject_Player");
WNAME_TAG(PROTO_OBJ_BODY_PLAYER, L"Prototype_GameObject_Body_Player");
WNAME_TAG(PROTO_OBJ_WEAPON, L"Prototype_GameObject_Weapon");
WNAME_TAG(PROTO_OBJ_SKY, L"Prototype_GameObject_Sky");
WNAME_TAG(PROTO_OBJ_SNOW, L"Prototype_GameObject_Snow");
WNAME_TAG(PROTO_OBJ_EXPLOSION, L"Prototype_GameObject_Explosion");
WNAME_TAG(PROTO_OBJ_EFT_STAR, L"Prototype_GameObject_Effect_Star");
WNAME_TAG(PROTO_OBJ_EFFECT_TEST_SINGLE, L"Prototype_GameObject_Effect_Test_Single");
WNAME_TAG(PROTO_OBJ_PARTICLE_EMITTER, L"Prototype_GameObject_Particle_Emitter");

WNAME_TAG(PROTO_OBJ_BATTLE_TRAINER, L"Prototype_GameObject_Battle_Trainer");
WNAME_TAG(PROTO_OBJ_BATTLE_BALL, L"Prototype_GameObject_Battle_Ball");

WNAME_TAG(PROTO_BTN_GLOW_MENU_PARTNER, L"Prototype_UIButton_Glow_Menu_Partner");
WNAME_TAG(PROTO_BTN_GLOW_MENU_SQUARE, L"Prototype_UIButton_Glow_Menu_Square");
WNAME_TAG(PROTO_BTN_LAYERED_GET, L"Prototype_UIButton_Layered_Get");
WNAME_TAG(PROTO_BTN_LAYERED_BTL_COMMAND, L"Prototype_UIButton_Layered_Battle_Command");
WNAME_TAG(PROTO_BTN_ENTRY_PLATE, L"Prototype_UIButton_Entry_Plate");
WNAME_TAG(PROTO_IMG_FADEBATTLE, L"Prototype_UIImage_FadeBattle");

WNAME_TAG(PROTO_OBJ_PLAYER_LGPE, L"Prototype_GameObject_Player_LGPE");
WNAME_TAG(PROTO_OBJ_PLAYER_STATE, L"Prototype_GameObject_PlayerState");

WNAME_TAG(PROTO_OBJ_BODY_HERO, L"Prototype_GameObject_Body_Hero");
WNAME_TAG(PROTO_OBJ_BODY_POKEMON, L"Prototype_GameObject_Body_Pokemon");
WNAME_TAG(PROTO_OBJ_BODY_HUMAN, L"Prototype_GameObject_Body_Human");

WNAME_TAG(PROTO_OBJ_ACTOR_NPC, L"Prototype_GameObject_Actor_NPC");
WNAME_TAG(PROTO_OBJ_ACTOR_WILD_POKEMON, L"Prototype_GameObject_Actor_WildPokemon");
WNAME_TAG(PROTO_OBJ_ACTOR_CAPTURE_TARGET, L"Prototype_GameObject_Actor_CaptureTarget");

WNAME_TAG(PROTO_MAP_TOWN01, L"Prototype_MapObject_Town01");
WNAME_TAG(PROTO_MAP_TOWN02, L"Prototype_MapObject_Town02");
WNAME_TAG(PROTO_MAP_ROAD01, L"Prototype_MapObject_Road01");
WNAME_TAG(PROTO_BMAP_TOWN, L"Prototype_BattleMap_Town");
WNAME_TAG(PROTO_BMAP_GRASS, L"Prototype_BattleMap_Grass");

WNAME_TAG(PROTO_OBJ_MONSTER_BALL, L"Prototype_GameObject_MonsterBall");
WNAME_TAG(PROTO_OBJ_CAPTURE_RING, L"Prototype_GameObject_CaptureRing");
WNAME_TAG(PROTO_OBJ_FIELD_GRASS, L"Prototype_GameObject_FieldGrass");
WNAME_TAG(PROTO_OBJ_FIELD_GRASS_BATCH, L"Prototype_GameObject_FieldGrassBatch");
WNAME_TAG(PROTO_OBJ_EFFECT, L"Prototype_GameObject_Effect");
WNAME_TAG(PROTO_OBJ_EFFECT_MESH, L"Prototype_GameObject_Effect_Mesh");
WNAME_TAG(PROTO_OBJ_TRAIL, L"Prototype_GameObject_Trail");

// Component
WNAME_TAG(COM_TEXTURE_DIFF, L"Com_Texture_Diffuse");
WNAME_TAG(COM_TEXTURE_MASK, L"Com_Texture_Mask");
WNAME_TAG(COM_TEXTURE_BRUSH, L"Com_Texture_Brush");
WNAME_TAG(COM_TEXTURE_NOISE, L"Com_Texture_Noise");

WNAME_TAG(COM_INTERACTION_DIALOGUE, L"Com_Interaction_Dialogue");
WNAME_TAG(COM_INTERACTION_ENCOUNTER, L"Com_Interaction_Encounter");
WNAME_TAG(COM_INTERACTION_BALLHIT, L"Com_Interaction_BallHit");
WNAME_TAG(COM_INTERACTION_DIALOGUE_BATTLE, L"Com_Interaction_Dialogue_Battle");
WNAME_TAG(COM_INTERACTION_EVENTSEQUENCE, L"Com_Interaction_EventSequence");

// Part
WNAME_TAG(PART_BODY, L"Part_Body");
WNAME_TAG(PART_BALL, L"Part_Ball");
WNAME_TAG(PART_WEAPON, L"Part_Weapon");



// Font
WNAME_TAG(FONT_MALGUN, L"Font_Malgun");
WNAME_TAG(FONT_NANUMBARUNGOTHIC, L"Font_NanumBarunGothic");
WNAME_TAG(FONT_NOTOSANSKR, L"Font_NotoSansKR");

NS_END

#endif // Game_PKM_Tags_h__